import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import localFont from 'next/font/local'
import Table from "./components/Table";
import ContentPrice from "./components/Content";
import Grid from "./components/Grid";
import Quetions from "./components/Quetions";
import Utp from './components/Utp';
import About from "./components/About";
import Phone from "./components/Phone";





export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body>
        <Header />
        <Table />
        <About />
        <ContentPrice />
        <Utp />
        <Grid />
        <Quetions />
        {/* <Phone />  */}
        {/* <main className="container mx-auto min-h-screen">{children}
          
        </main> */}
        <Footer />
      </body>
    </html>
  );
}
