import './globals.css'
import HamburgerMenu from './components/HamburgerMenu'
import { Nunito } from 'next/font/google'
import Head from 'next/head'
import Footer from './components/Footer' 
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';


// const nunito = Nunito({
//   subsets: ['cyrillic'],
//   display: 'swap',
// })

export default function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Творческая студия Вики Борщ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      

 
      <main>
        <Component {...pageProps} />
        <Footer />
      </main>
    </>
  )
}
